import 'package:flutter/material.dart';

/// Theme catalog for Kakuro's "mathematician's chalkboard study".
///
/// Every colorway stays inside the physical study world — slate, paper,
/// chalk, ink, oak, lamplight. Variety comes from different board
/// materials, chalk tints, frame woods and lamp washes. No neon, no glow.
class ChalkThemeDef {
  final String id;
  final String name;
  final bool isPro;
  final Color board; // slate/paper surface
  final Color boardDeep; // clue cells (darker than board)
  final Color entry; // entry cell fill
  final Color chalk; // primary chalk lettering
  final Color chalkDim; // secondary chalk (clue sums, labels)
  final Color accent; // selection outline, stars (amber family)
  final Color frame; // oak rim
  final Color frameDeep; // oak shadow edge
  final Color desk; // screen background
  final Color lamp; // warm lamp wash tint
  final Color error; // red chalk
  final Color pencil; // pencil-mark tint

  const ChalkThemeDef({
    required this.id,
    required this.name,
    required this.isPro,
    required this.board,
    required this.boardDeep,
    required this.entry,
    required this.chalk,
    required this.chalkDim,
    required this.accent,
    required this.frame,
    required this.frameDeep,
    required this.desk,
    required this.lamp,
    required this.error,
    required this.pencil,
  });
}

class ChalkThemes {
  /// First 5 are FREE. The rest are PRO.
  static const List<String> freeThemeIds = [
    'classic-slate',
    'midnight-study',
    'forest-board',
    'desert-paper',
    'river-ink',
  ];

  static bool isProTheme(String id) =>
      !freeThemeIds.contains(id) && id != 'custom';

  static const List<ChalkThemeDef> all = [
    // ---------------------------------------------------------- FREE
    ChalkThemeDef(
      id: 'classic-slate',
      name: 'Classic Slate',
      isPro: false,
      board: Color(0xFF1E2522),
      boardDeep: Color(0xFF171C1A),
      entry: Color(0xFF232B27),
      chalk: Color(0xFFF4E8B0),
      chalkDim: Color(0xFFB9AC7E),
      accent: Color(0xFFC98544),
      frame: Color(0xFF7A4B20),
      frameDeep: Color(0xFF4A2C11),
      desk: Color(0xFF12140F),
      lamp: Color(0xFFC98544),
      error: Color(0xFFD06048),
      pencil: Color(0xFF8CA891),
    ),
    ChalkThemeDef(
      id: 'midnight-study',
      name: 'Midnight Study',
      isPro: false,
      board: Color(0xFF1A2233),
      boardDeep: Color(0xFF131A28),
      entry: Color(0xFF1F2940),
      chalk: Color(0xFFEDECE4),
      chalkDim: Color(0xFF9AA4BC),
      accent: Color(0xFFD9A441),
      frame: Color(0xFF5A3A22),
      frameDeep: Color(0xFF38220F),
      desk: Color(0xFF0D1119),
      lamp: Color(0xFFD9A441),
      error: Color(0xFFD06048),
      pencil: Color(0xFF8FB3C7),
    ),
    ChalkThemeDef(
      id: 'forest-board',
      name: 'Forest Board',
      isPro: false,
      board: Color(0xFF1C2A20),
      boardDeep: Color(0xFF142017),
      entry: Color(0xFF223026),
      chalk: Color(0xFFF1E7C4),
      chalkDim: Color(0xFFA8B394),
      accent: Color(0xFFC99A4B),
      frame: Color(0xFF6B4423),
      frameDeep: Color(0xFF422712),
      desk: Color(0xFF10160F),
      lamp: Color(0xFFC99A4B),
      error: Color(0xFFC65B43),
      pencil: Color(0xFF9DBE8C),
    ),
    ChalkThemeDef(
      id: 'desert-paper',
      name: 'Desert Paper',
      isPro: false,
      board: Color(0xFFE8DCC0),
      boardDeep: Color(0xFFD9CBA9),
      entry: Color(0xFFF2E8D2),
      chalk: Color(0xFF4A3A26),
      chalkDim: Color(0xFF8A7554),
      accent: Color(0xFFB4712A),
      frame: Color(0xFF7A4B20),
      frameDeep: Color(0xFF4A2C11),
      desk: Color(0xFFC9B78E),
      lamp: Color(0xFFFFF3D6),
      error: Color(0xFFB0402A),
      pencil: Color(0xFF6E8F5E),
    ),
    ChalkThemeDef(
      id: 'river-ink',
      name: 'River Ink',
      isPro: false,
      board: Color(0xFFDDE4E4),
      boardDeep: Color(0xFFCBD4D4),
      entry: Color(0xFFE8EDED),
      chalk: Color(0xFF1F3A4D),
      chalkDim: Color(0xFF5E7A8C),
      accent: Color(0xFF9A5F22),
      frame: Color(0xFF5C4026),
      frameDeep: Color(0xFF3A2712),
      desk: Color(0xFFB9C4C2),
      lamp: Color(0xFFFFFFFF),
      error: Color(0xFFA83A24),
      pencil: Color(0xFF4E7A68),
    ),
    // ---------------------------------------------------------- PRO
    ChalkThemeDef(
      id: 'charcoal-night',
      name: 'Charcoal Night',
      isPro: true,
      board: Color(0xFF191919),
      boardDeep: Color(0xFF111111),
      entry: Color(0xFF202020),
      chalk: Color(0xFFF5F0E0),
      chalkDim: Color(0xFFA8A094),
      accent: Color(0xFFD9A441),
      frame: Color(0xFF3A3A3A),
      frameDeep: Color(0xFF1E1E1E),
      desk: Color(0xFF0B0B0B),
      lamp: Color(0xFFD9A441),
      error: Color(0xFFD06048),
      pencil: Color(0xFF9AA8B0),
    ),
    ChalkThemeDef(
      id: 'terracotta-dusk',
      name: 'Terracotta Dusk',
      isPro: true,
      board: Color(0xFF2E1F1A),
      boardDeep: Color(0xFF231712),
      entry: Color(0xFF37251F),
      chalk: Color(0xFFF6E3C2),
      chalkDim: Color(0xFFB99A78),
      accent: Color(0xFFE08A3C),
      frame: Color(0xFF8A4A24),
      frameDeep: Color(0xFF552A10),
      desk: Color(0xFF1A100C),
      lamp: Color(0xFFE08A3C),
      error: Color(0xFFD0553A),
      pencil: Color(0xFFA8B08A),
    ),
    ChalkThemeDef(
      id: 'moss-amber',
      name: 'Moss & Amber',
      isPro: true,
      board: Color(0xFF232A18),
      boardDeep: Color(0xFF1A2011),
      entry: Color(0xFF2A321E),
      chalk: Color(0xFFF2E6BC),
      chalkDim: Color(0xFFA3AC82),
      accent: Color(0xFFE0A83C),
      frame: Color(0xFF6E4E22),
      frameDeep: Color(0xFF45300F),
      desk: Color(0xFF141809),
      lamp: Color(0xFFE0A83C),
      error: Color(0xFFC65B43),
      pencil: Color(0xFFB0C48A),
    ),
    ChalkThemeDef(
      id: 'indigo-lecture',
      name: 'Indigo Lecture',
      isPro: true,
      board: Color(0xFF1E1E3A),
      boardDeep: Color(0xFF15152A),
      entry: Color(0xFF252544),
      chalk: Color(0xFFEFE9F5),
      chalkDim: Color(0xFF9A94B8),
      accent: Color(0xFFD9A441),
      frame: Color(0xFF4A3420),
      frameDeep: Color(0xFF2C1E0E),
      desk: Color(0xFF101022),
      lamp: Color(0xFFD9A441),
      error: Color(0xFFD06048),
      pencil: Color(0xFF9AB0D0),
    ),
    ChalkThemeDef(
      id: 'sepia-archive',
      name: 'Sepia Archive',
      isPro: true,
      board: Color(0xFFE4D3AC),
      boardDeep: Color(0xFFD4C194),
      entry: Color(0xFFEEDDBB),
      chalk: Color(0xFF3E2C18),
      chalkDim: Color(0xFF7E6A48),
      accent: Color(0xFF9A5F22),
      frame: Color(0xFF6B4423),
      frameDeep: Color(0xFF422712),
      desk: Color(0xFFC2A878),
      lamp: Color(0xFFFFF6DC),
      error: Color(0xFFA83A24),
      pencil: Color(0xFF5E7A52),
    ),
    ChalkThemeDef(
      id: 'plum-chalk',
      name: 'Plum Chalk',
      isPro: true,
      board: Color(0xFF2A1E2E),
      boardDeep: Color(0xFF1F1522),
      entry: Color(0xFF332538),
      chalk: Color(0xFFF3E4EE),
      chalkDim: Color(0xFFAE94A8),
      accent: Color(0xFFD9A441),
      frame: Color(0xFF5C3A3E),
      frameDeep: Color(0xFF3A2226),
      desk: Color(0xFF160F18),
      lamp: Color(0xFFD9A441),
      error: Color(0xFFD06048),
      pencil: Color(0xFFA8B89A),
    ),
    ChalkThemeDef(
      id: 'ocean-slate',
      name: 'Ocean Slate',
      isPro: true,
      board: Color(0xFF16282E),
      boardDeep: Color(0xFF0F1E23),
      entry: Color(0xFF1C3038),
      chalk: Color(0xFFEAF2EE),
      chalkDim: Color(0xFF8AA4A0),
      accent: Color(0xFFD9A441),
      frame: Color(0xFF54402A),
      frameDeep: Color(0xFF332512),
      desk: Color(0xFF0B1518),
      lamp: Color(0xFFD9A441),
      error: Color(0xFFD06048),
      pencil: Color(0xFF8AC0B0),
    ),
    ChalkThemeDef(
      id: 'ember-board',
      name: 'Ember Board',
      isPro: true,
      board: Color(0xFF2B1A12),
      boardDeep: Color(0xFF201209),
      entry: Color(0xFF352016),
      chalk: Color(0xFFF6E8CC),
      chalkDim: Color(0xFFB08E66),
      accent: Color(0xFFF08030),
      frame: Color(0xFF7A3A18),
      frameDeep: Color(0xFF4A2008),
      desk: Color(0xFF150C06),
      lamp: Color(0xFFF08030),
      error: Color(0xFFE04A28),
      pencil: Color(0xFFB0A07A),
    ),
    ChalkThemeDef(
      id: 'sage-paper',
      name: 'Sage Paper',
      isPro: true,
      board: Color(0xFFDDE0CC),
      boardDeep: Color(0xFFCCD0B4),
      entry: Color(0xFFE6E9D8),
      chalk: Color(0xFF2E3A24),
      chalkDim: Color(0xFF6E7A5E),
      accent: Color(0xFF9A5F22),
      frame: Color(0xFF6B4E2A),
      frameDeep: Color(0xFF42300F),
      desk: Color(0xFFBCC09E),
      lamp: Color(0xFFFFFFFF),
      error: Color(0xFFA83A24),
      pencil: Color(0xFF4E6E48),
    ),
    ChalkThemeDef(
      id: 'cobalt-night',
      name: 'Cobalt Night',
      isPro: true,
      board: Color(0xFF141E33),
      boardDeep: Color(0xFF0D1526),
      entry: Color(0xFF1A2540),
      chalk: Color(0xFFF0EFE8),
      chalkDim: Color(0xFF8E9AB5),
      accent: Color(0xFFC98544),
      frame: Color(0xFF3E3222),
      frameDeep: Color(0xFF241C0E),
      desk: Color(0xFF090E1A),
      lamp: Color(0xFFC98544),
      error: Color(0xFFD06048),
      pencil: Color(0xFF8FA8C8),
    ),
  ];

  static ChalkThemeDef byId(String id, {required ChalkThemeDef custom}) {
    if (id == 'custom') return custom;
    for (final t in all) {
      if (t.id == id) return t;
    }
    return all.first;
  }
}
